training_pipeline:
  pipeline:
    stages:
      - load_data
      - clean_data
      - train_model
      - evaluate_model

  training:
    model_type: "lstm"                  # Options: lstm | cnn | cnn_lstm | logistic_regression
    target_column: "sentiment"          # Column to predict
    config_path: "configs/config.yaml"  # General config (data + logging + env)
    model_params_path: "configs/model_params.yaml"

  evaluation:
    save_dir: "artifacts/evaluation"
    best_model_dir: "artifacts/best_model"
