pipeline:
  stages:
    - name: data_ingestion
      script: src/pipeline/stage_01_data_ingestion.py
    - name: data_validation
      script: src/pipeline/stage_02_data_validation.py
    - name: data_transformation
      script: src/pipeline/stage_03_data_transformation.py
    - name: model_training
      script: src/pipeline/stage_04_model_training.py
    - name: model_evaluation
      script: src/pipeline/stage_05_model_evaluation.py
