training_pipeline:
  pipeline:
    stages:
      - load_data
      - clean_data
      - train_model
      - evaluate_model

  training:
    model_type: "logistic_regression"                  # Options: lstm | cnn | cnn_lstm | logistic_regression
    target_column: "sentiment"          # Column to predict
    config_path: "configs/config.yaml"  # General config (data + logging + env)
    model_params_path: "configs/model_params.yaml"

  evaluation:
    save_dir: "artifacts/evaluation"
    best_model_dir: "artifacts/best_model"


evaluation_pipeline:
  data:
    cleaned_data_path: "data/processed/cleaned_data.csv"

  models:
    source_dir: "artifacts/models"
    evaluate_all: True
    selected_model: "lstm"
    train_all_models: true   
    train_models_if_missing: true

  evaluation:
    save_dir: "artifacts/evaluation"
    best_model_dir: "artifacts/best_model"

  training:
    config_path: "configs/config.yaml"
    model_params_path: "configs/model_params.yaml"
    target_column: "sentiment"
